config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kickboxers
  # get '/kickboxers', to: 'kickboxers#index'
  # get '/kickboxers/:id', to: 'kickboxers#show', as: "kickboxer"
  get '/headliner/:fighter_one/:fighter_two', to: 'kickboxers#headliner', as: "headliner"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kickboxer.rb
class Kickboxer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kickboxers_controller.rb
class KickboxersController < ApplicationController
  before_action :set_kickboxer, only: [:show, :edit, :update, :destroy]

  def index
    @kickboxers = Kickboxer.all
  end

  def show
  end

  def new
    @kickboxer = Kickboxer.new
  end

  def create
    @kickboxer = Kickboxer.create(kickboxer_params)
    # @kickboxer = Kickboxer.create(name: params[:name], speed: params[:speed], fist_size: params[:fist_size], missing_teeth: params[:missing_teeth], villain: params[:villain])
    redirect_to @kickboxer
  end

  # get "/kickboxers/:id/edit"
  def edit
  end

  def update
    @kickboxer.update(kickboxer_params)
    redirect_to @kickboxer
  end

  def destroy
    @kickboxer.destroy
    redirect_to kickboxers_path
  end


  def headliner
    @kickboxer_1 = Kickboxer.find(params[:fighter_one])
    @kickboxer_2 = Kickboxer.find(params[:fighter_two])
  end

  private

  def kickboxer_params
    params.require(:kickboxer).permit(:name, :speed, :fist_size, :missing_teeth, :villain)
  end

  def set_kickboxer
    @kickboxer = Kickboxer.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kickboxers_helper.rb
module KickboxersHelper
end

app/views/kickboxers/_form.html.erb
<%= form_for @kickboxer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :speed %>
  <%= f.number_field :speed %>
  <%= f.label :fist_size %>
  <%= f.number_field :fist_size %>
  <%= f.label :missing_teeth %>
  <%= f.number_field :missing_teeth %>
  <%= f.label :villain %>
  <%= f.check_box :villain %>
  <%= f.submit %>
<% end %>

app/views/kickboxers/edit.html.erb
<h1>UPDATE <%= @kickboxer.name.upcase %></h1>

<%# form_for is useful for creating a form related to a model %>

<%= render "form" %>

app/views/kickboxers/headliner.html.erb
<h1><%= @kickboxer_1.name %> vs <%= @kickboxer_2.name %></h1>
<h3>SUNDAY SUNDAY SUNDAY</h3>

app/views/kickboxers/index.html.erb
<h1>Welcome to the index page for kickboxers</h1>

<ul>
<% @kickboxers.each do |kickboxer| %>
  <li><%= link_to kickboxer.name, kickboxer %></li>
<% end %>
</ul>

app/views/kickboxers/new.html.erb
<h1>CREATE YOUR FIGHTER</h1>

<%# Use the form partial %>
<%= render "form" %>


<% if false %>
<%# form_for is useful for creating a form related to a model %>

<%= form_for @kickboxer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :speed %>
  <%= f.number_field :speed %>
  <%= f.label :fist_size %>
  <%= f.number_field :fist_size %>
  <%= f.label :missing_teeth %>
  <%= f.number_field :missing_teeth %>
  <%= f.label :villain %>
  <%= f.check_box :villain %>
  <%= f.submit %>
<% end %>

<% end %>

<%#Don't use regular HTML FORMS in Rails. If you do, you need an authenticity token!%>

<% if false %>
<form action="/kickboxers" method="post">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
  <label for="name">Name:</label>
  <input type="text" name="kickboxer[name]"><br/>
  <label for="speed">Speed:</label>
  <input type="integer" name="kickboxer[speed]"><br/>
  <label for="fist_size">Fist Size:</label>
  <input type="integer" name="kickboxer[fist_size]"><br/>
  <label for="missing_teeth">Missing Teeth:</label>
  <input type="integer" name="kickboxer[missing_teeth]"><br/>
  <label for="villain">Villain:</label>
  <input type="checkbox" name="kickboxer[villain]"><br/>
  <input type="submit" value="Submit">
  </form>
<% end %>

<%# Form tag is most useful when creating a form that is not related to creating or updating a RESTful resource %>
<%if false%>
<%= form_tag "/kickboxers", method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :speed %>
  <%= number_field_tag :speed %>
  <%= label_tag :fist_size %>
  <%= number_field_tag :fist_size %>
  <%= label_tag :missing_teeth %>
  <%= number_field_tag :missing_teeth %>
  <%= label_tag "Villain" %>
  <%= check_box_tag :villain %>
  <%= submit_tag "Submit!" %>
<% end %>
<% end %>

app/views/kickboxers/show.html.erb
<h1><%= @kickboxer.name %></h1>
<p><strong>Speed: </strong><%= @kickboxer.speed %></p>
<p><strong>Fist Size: </strong><%= @kickboxer.fist_size %></p>
<p><strong>Missing Teeth: </strong><%= @kickboxer.missing_teeth %></p>
<p><strong>Status: </strong><%= @kickboxer.villain ? "Heel" : "Face" %></p>
<%= link_to "Edit this Kickboxer", edit_kickboxer_path(@kickboxer)  %>
<%= button_to "FINISH HIM", kickboxer_path(@kickboxer), method: :delete %>

app/views/layouts/_nav.html.erb
<%= link_to "See All Kickboxers", kickboxers_path %> |
<%= link_to "Create a Kickboxer", new_kickboxer_path %> |
<%= link_to "See Headliner", headliner_path(Kickboxer.first.id, Kickboxer.last.id) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer><%= render "layouts/nav" %></footer>
  </body>
</html>